In [1]:
import numpy as np

# Transform into numpy array

In [2]:
my_list = [1,2,3]
np.array(my_list)

array([1, 2, 3])

In [3]:
arr = np.array(my_list)
arr

array([1, 2, 3])

# Create numpy array

In [4]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [5]:
np.zeros((5,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [6]:
np.ones(7)

array([1., 1., 1., 1., 1., 1., 1.])

In [7]:
np.linspace(0,10,11)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [8]:
np.linspace(0,10,4)

array([ 0.        ,  3.33333333,  6.66666667, 10.        ])

In [9]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# Random distribution

In [10]:
np.random.rand(5,2)

array([[0.21679823, 0.8431503 ],
       [0.0204199 , 0.4245039 ],
       [0.30187064, 0.36191849],
       [0.23787572, 0.42010985],
       [0.8359497 , 0.70821438]])

In [11]:
np.random.randn(5,2)

array([[ 0.20783033, -0.83470267],
       [-1.93793198, -0.78096912],
       [ 0.5580348 ,  1.76769083],
       [ 1.02520465, -2.39145519],
       [ 0.10183992, -1.22811013]])

In [12]:
np.random.randint(0,101,5)

array([65, 58, 64, 76, 29])

In [13]:
np.random.randint(0,101,(4,5))

array([[ 25,  64,   5,  76,  34],
       [ 92,  83,  71,  72,   2],
       [ 58,  88, 100,  92,  97],
       [ 23,  64,  28,  16,  89]])

In [17]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

# Useful

In [19]:
arr = np.arange(0, 25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [20]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [22]:
ranarr = np.random.randint(0, 101, 10)
ranarr

array([ 1, 87, 29, 37,  1, 63, 59, 20, 32, 75])

In [23]:
ranarr.max()

87

In [26]:
ranarr.min()

1

In [27]:
ranarr.argmax()

1

In [28]:
ranarr.argmin()

0

In [29]:
ranarr.dtype

dtype('int64')

In [30]:
ranarr.shape

(10,)

---

# Indexing and Selection

In [32]:
arr = np.arange(0,11)

In [33]:
arr[8]

8

In [34]:
arr[1:4]

array([1, 2, 3])

In [35]:
arr[:5]

array([0, 1, 2, 3, 4])

In [36]:
arr[7:]

array([ 7,  8,  9, 10])

In [37]:
arr[:]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

#### 2D
---

In [39]:
arr_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [40]:
arr_2d[0]

array([1, 2, 3])

In [41]:
arr_2d[1][1]

5

In [42]:
arr_2d[1,1]

5

In [43]:
arr_2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [44]:
arr_2d[:2,1:]

array([[2, 3],
       [5, 6]])

### Broadcasting
---

In [45]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [46]:
arr[0:5] = 100
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [47]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [49]:
sliced_arr = arr[:5]
sliced_arr

array([0, 1, 2, 3, 4])

In [50]:
sliced_arr[:] = 99
sliced_arr

array([99, 99, 99, 99, 99])

In [51]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

------ Should make independent copy

In [52]:
arr = np.arange(0,11)
copy_arr = arr[:5].copy()

print(arr)
print(copy_arr)

[ 0  1  2  3  4  5  6  7  8  9 10]
[0 1 2 3 4]


In [53]:
copy_arr[:] = 69


print(arr)
print(copy_arr)

[ 0  1  2  3  4  5  6  7  8  9 10]
[69 69 69 69 69]


### Conditional Selection
---

In [54]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [55]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [56]:
bool_arr = arr > 4
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [57]:
arr[arr>4]

array([ 5,  6,  7,  8,  9, 10])

# Numpy Operations
---

In [58]:
arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [59]:
arr + 5

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [60]:
arr - 2

array([-2, -1,  0,  1,  2,  3,  4,  5,  6,  7])

In [61]:
arr * 4

array([ 0,  4,  8, 12, 16, 20, 24, 28, 32, 36])

In [62]:
arr / 6

array([0.        , 0.16666667, 0.33333333, 0.5       , 0.66666667,
       0.83333333, 1.        , 1.16666667, 1.33333333, 1.5       ])

In [63]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [64]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [65]:
arr * arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [66]:
arr / arr

/tmp/ipykernel_10845/3001117470.py:1: RuntimeWarning: invalid value encountered in divide
  arr / arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [67]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [68]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [69]:
np.log(arr)

/tmp/ipykernel_10845/3120950136.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

### Summary statistics
---

In [71]:
arr = np.arange(0, 10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [72]:
arr.sum()

45

In [73]:
arr.mean()

4.5

In [74]:
arr.var()

8.25

In [75]:
arr.std()

2.8722813232690143

In [76]:
arr_2d = np.arange(0,25).reshape(5,5)
arr_2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [77]:
arr_2d.sum()

300

In [78]:
arr_2d.sum(axis=0) # perform this operation across the rows (summ colums like 0 + 5 + 10 + 15 + 20)

array([50, 55, 60, 65, 70])

In [79]:
arr_2d.sum(axis=1)

array([ 10,  35,  60,  85, 110])